all: simple-example streaming-example

simple-example:
	cd .. && elm make --warn examples/simple/Simple.elm --output=examples/simple/simple.js

streaming-example:
	cd .. && elm make --warn examples/streaming/Streaming.elm --output=examples/streaming/streaming.js
